### ISSUE TITLE
Is it possible to have an option to set color mode without the alpha? ie straight hex value

### ISSUE THREAD

**Issue by treforcoster** [advplyr/vue-tailwind-color-picker#3]

**Comment by advplyr** [comment]
Yes, just press the arrows next to the rgba input.

**Comment by treforcoster** [comment]
HI thanks for replying... the arrows switch from RGBA to HEX with Alpha

I wanted HEX only and to be able to set this as a default mode.. are there any options to do this?

Thanks

**Comment by advplyr** [comment]
There is no way to do it currently
